// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "A66.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[Swap two values]")
{
	int n1, n2, n3;
	int max, min;
	n1 = 10;
	n2 = 20;
	n3 = 30;
	maxmin(n1, n2, n3, max, min);
	REQUIRE(max == 30);
	REQUIRE(min == 10);
	n1 = 20;
	n2 = 10;
	n3 = 30;
	maxmin(n1, n2, n3, max, min);
	REQUIRE(max == 30);
	REQUIRE(min == 10);
	n1 = 30;
	n2 = 20;
	n3 = 10;
	maxmin(n1, n2, n3, max, min);
	REQUIRE(max == 30);
	REQUIRE(min == 10);
}